// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'FilterOverlay': typeof import("../components/FilterOverlay.vue")['default'],
    'GamesPagination': typeof import("../components/GamesPagination.vue")['default'],
    'GamesPaginationButton': typeof import("../components/GamesPaginationButton.vue")['default'],
    'AdminGameDetail': typeof import("../components/admin/GameDetail.vue")['default'],
    'Header': typeof import("../components/header/Header.vue")['default'],
    'BaseLoadingSpinner': typeof import("../components/base/LoadingSpinner.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyFilterOverlay': typeof import("../components/FilterOverlay.vue")['default'],
    'LazyGamesPagination': typeof import("../components/GamesPagination.vue")['default'],
    'LazyGamesPaginationButton': typeof import("../components/GamesPaginationButton.vue")['default'],
    'LazyAdminGameDetail': typeof import("../components/admin/GameDetail.vue")['default'],
    'LazyHeader': typeof import("../components/header/Header.vue")['default'],
    'LazyBaseLoadingSpinner': typeof import("../components/base/LoadingSpinner.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const FilterOverlay: typeof import("../components/FilterOverlay.vue")['default']
export const GamesPagination: typeof import("../components/GamesPagination.vue")['default']
export const GamesPaginationButton: typeof import("../components/GamesPaginationButton.vue")['default']
export const AdminGameDetail: typeof import("../components/admin/GameDetail.vue")['default']
export const Header: typeof import("../components/header/Header.vue")['default']
export const BaseLoadingSpinner: typeof import("../components/base/LoadingSpinner.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyFilterOverlay: typeof import("../components/FilterOverlay.vue")['default']
export const LazyGamesPagination: typeof import("../components/GamesPagination.vue")['default']
export const LazyGamesPaginationButton: typeof import("../components/GamesPaginationButton.vue")['default']
export const LazyAdminGameDetail: typeof import("../components/admin/GameDetail.vue")['default']
export const LazyHeader: typeof import("../components/header/Header.vue")['default']
export const LazyBaseLoadingSpinner: typeof import("../components/base/LoadingSpinner.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
